# Generated by Django 4.1 on 2022-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True, verbose_name='является активным покупателем'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bottle_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
